apiVersion: apps/v1
kind: Deployment
metadata:
  name: olli-forecast-sales
  labels:
    app: olli-forecast-sales
spec:
  replicas: 2
  selector:
    matchLabels:
      app: olli-forecast-sales
  template:
    metadata:
      labels:
        app: olli-forecast-sales
    spec:
      containers:
      - name: olli-forecast-sales
        image: ollisalesforecast.azurecr.io/olli-forecast-sales:latest
        ports:
        - containerPort: 8000
        env:
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: subscription-id
        - name: AZURE_RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: resource-group
        - name: AZURE_WORKSPACE_NAME
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: workspace-name
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: olli-forecast-sales
spec:
  selector:
    app: olli-forecast-sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: olli-forecast-sales
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: olli-forecast-sales
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
