apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: olli-forecast-sales
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: olli-forecast-sales
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olli-forecast-sales
  labels:
    release: prometheus
spec:
  groups:
  - name: olli-forecast-sales
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
        /
        sum(rate(http_requests_total[5m])) by (service)
        > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
        description: Error rate is above 10% for 5 minutes

    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))
        > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: 95th percentile latency is above 2 seconds for 5 minutes

    - alert: ModelPredictionError
      expr: |
        prediction_error_rate > 0.2
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: High model prediction error
        description: Model prediction error rate is above 20% for 15 minutes
